# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('already_used', models.BooleanField(default=False)),
                ('stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
