# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='stamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
