# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20161201_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='number_of_voters',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
