# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20170622_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='choices',
            field=models.CharField(help_text='\t\t[{"text": "Alain Juppé", "slug": "alain-juppe"}, {"text": "François Fillon", "slug": "francois-fillon"}]', max_length=1024),
        ),
    ]
