# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20171015_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='max_number_of_choices',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
